# Generated by Django 3.2.6 on 2021-09-02 18:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('section', models.CharField(choices=[('s1', 'Section1'), ('s2', 'Section2')], max_length=10)),
                ('type', models.CharField(choices=[('bool', 'boolean'), ('choice', 'choice'), ('num', 'number')], max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_num', models.IntegerField(null=True, unique=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_trial', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices_answer', models.CharField(blank=True, choices=[('b2c', 'B2C'), ('b2b', 'B2B'), ('both', 'Both'), ('y', 'Yes'), ('n', 'No')], max_length=5, null=True)),
                ('int_answer', models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answer', to='business_plan_app.question')),
                ('trial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trial_number', to='business_plan_app.usertrial')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_answer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
