# Generated by Django 3.2.6 on 2021-08-30 16:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_plan_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='investment_answer',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
