# Generated by Django 3.2.6 on 2021-08-30 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_plan_app', '0002_answer_investment_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='investment_answer',
        ),
    ]
