# Generated by Django 3.2.6 on 2021-08-30 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business_plan_app', '0005_auto_20210830_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=50, null=True)),
                ('user_try_number', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='businessplan',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='businessplan',
            name='question',
        ),
        migrations.RemoveField(
            model_name='businessplan',
            name='user',
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('bool', 'boolean'), ('choice', 'choice'), ('num', 'number')], max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='BusinessPlan',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answer', to='business_plan_app.question'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_answer', to=settings.AUTH_USER_MODEL),
        ),
    ]
