# Generated by Django 3.2.6 on 2021-08-31 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business_plan_app', '0006_auto_20210830_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='user_try_number',
        ),
        migrations.CreateModel(
            name='UserTrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_num', models.IntegerField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_trial', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='useranswer',
            name='trial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trial_number', to='business_plan_app.usertrial'),
        ),
    ]
