# Generated by Django 3.2.6 on 2021-08-31 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_plan_app', '0007_auto_20210831_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertrial',
            name='trial_num',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
